require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/business_regulations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BusinessRegulation. As you add validations to BusinessRegulation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BusinessRegulation.create! valid_attributes
      get business_regulations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      business_regulation = BusinessRegulation.create! valid_attributes
      get business_regulation_url(business_regulation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_business_regulation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      business_regulation = BusinessRegulation.create! valid_attributes
      get edit_business_regulation_url(business_regulation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BusinessRegulation" do
        expect {
          post business_regulations_url, params: { business_regulation: valid_attributes }
        }.to change(BusinessRegulation, :count).by(1)
      end

      it "redirects to the created business_regulation" do
        post business_regulations_url, params: { business_regulation: valid_attributes }
        expect(response).to redirect_to(business_regulation_url(BusinessRegulation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BusinessRegulation" do
        expect {
          post business_regulations_url, params: { business_regulation: invalid_attributes }
        }.to change(BusinessRegulation, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post business_regulations_url, params: { business_regulation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested business_regulation" do
        business_regulation = BusinessRegulation.create! valid_attributes
        patch business_regulation_url(business_regulation), params: { business_regulation: new_attributes }
        business_regulation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the business_regulation" do
        business_regulation = BusinessRegulation.create! valid_attributes
        patch business_regulation_url(business_regulation), params: { business_regulation: new_attributes }
        business_regulation.reload
        expect(response).to redirect_to(business_regulation_url(business_regulation))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        business_regulation = BusinessRegulation.create! valid_attributes
        patch business_regulation_url(business_regulation), params: { business_regulation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested business_regulation" do
      business_regulation = BusinessRegulation.create! valid_attributes
      expect {
        delete business_regulation_url(business_regulation)
      }.to change(BusinessRegulation, :count).by(-1)
    end

    it "redirects to the business_regulations list" do
      business_regulation = BusinessRegulation.create! valid_attributes
      delete business_regulation_url(business_regulation)
      expect(response).to redirect_to(business_regulations_url)
    end
  end
end
